spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/task_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:mypostgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false